name: Pages

on:
  push:
    branches:
      - master # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
#          key: ${{ runner.OS }}-npm-cache
          key: ${{ runner.OS }}-npm-${{ hashFiles('package-lock.json') }}-force  # 添加后缀强制刷新
          restore-keys: |
            ${{ runner.OS }}-npm-cache
# solution 
      - name: Install OS Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential python3  # 补全系统依赖
# 获取权限
      - name: Fix Hexo Permission
        run: chmod +x node_modules/.bin/hexo  # 关键！添加这一行

# solution
      - name: Install Dependencies
        run: npm install
# check
      - name: Debug Directory Structure
        run: |
          ls -al
          ls node_modules/.bin/  # 检查关键二进制文件是否存在

      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
# check
      - name: Check Node.js Availability
        run: |
          echo "Node.js path: $(which node)"
          echo "NPM path: $(which npm)"
          npm -v  # 确认命令可达